// react/pro4/src/root/components/pages/Login/Login.js
import React, { useState } from 'react';
import {useNavigate} from 'react-router-dom'
import { doLogin } from '../../../../services/UserService'
import { AlertDanger } from '../../../../shared/Alerts/Alert'

const Login = () => {

  let navigate = useNavigate();
  let [user, setUser] = useState({
    email : "",
    password : ""
  })

  let [showAlert, setShowAlert] = useState(false);
  let [msg, setMsg] = useState("");

  let submit = ()=>{
    doLogin(user).then(result=>{ 
      
      if(result.data.success == true)
      {
        localStorage.setItem("token", result.data.token);
        navigate("/profile");
      }

      if(result.data.errType == 1){
        setShowAlert(true);
        setMsg("This Email and Password is incorrect");
      }
      if(result.data.errType == 2){
        setShowAlert(true);
        setMsg("This Password is incorrect");
      }
    })
    .catch(err => console.log(err))
  }

  return (
    <div className="container" style={{minHeight : '700px'}}>
      <div className="row">
        <div className="col-md-6 offset-md-3">
          <h3>User Login</h3>
          <div className="form-group">
            <label htmlFor="">Email/Username</label>
            <input 
              type="text" 
              value={user.email} 
              onChange={(e)=>setUser({...user, email : e.target.value})} 
              className='form-control' />
          </div>
          <div className="form-group">
            <label htmlFor="">Password</label>
            <input 
              type="password" 
              value={user.password} 
              onChange={(e)=>setUser({...user, password : e.target.value})} 
              className='form-control' />
          </div>
          {
            showAlert ? <AlertDanger msg={msg} /> : ''
          }
          <br />
          <button className='btn btn-success' onClick={submit}>Login</button>
        </div>
      </div>
    </div>
  )
}

export default Login

// main-project/src/app/user/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  loginForm : FormGroup;
  checkForm = false;
  errMsg = "";
  
  constructor(
    private _fb : FormBuilder,
    private _auth : AuthService,
    private _router : Router
  ) {
    this.loginForm = this._fb.group({
      email : ["", [Validators.required, Validators.email]],
      password : ["", Validators.required]
    })
   }

  ngOnInit(): void {
  }

  submit(){
    if(this.loginForm.invalid){
      this.checkForm = true;
      return;
    }
    this._auth.doLogin(this.loginForm.value).subscribe(result=>{
      // console.log(result);
      if(result.success){
        localStorage.setItem("token", result.token);
        this._router.navigate(["/"]);
      }else{
        if(result.errType == 1){
          this.errMsg = "This Email/Username is not registred !";
        }
        if(result.errType == 2){
          this.errMsg = "This Password is not correct !";
        }
      }
    })
  }

}

<div class="container my-4">
    <form [formGroup]="loginForm">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h4>User Login</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="">Username/Email</label>
                        <input type="text" [ngClass]="{'is-invalid' : loginForm.controls['email'].errors && checkForm }" formControlName="email" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="">Password</label>
                        <input type="password" [ngClass]="{'is-invalid' : loginForm.controls['password'].errors && checkForm }" formControlName="password" class="form-control" />
                    </div>
                    <small class="text-danger">{{ errMsg }}</small>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Login" (click)="submit()" class="btn btn-primary" />
                    <br />
                    <a class="text-info" routerLink="/forgot-password">Forgot Password</a>
                </div>
            </div>
        </div>
    </div>
    </form>
</div>
