// json-project/src/app/pages/student/student.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { StudentService } from 'src/app/services/student.service';

@Component({
  selector: 'app-student',
  templateUrl: './student.component.html',
  styleUrls: ['./student.component.css']
})
export class StudentComponent implements OnInit {

  stuForm : FormGroup;
  checkForm = false;
  id:any;
  constructor(
    private _fb : FormBuilder,
    private _stu : StudentService,
    private _router : Router,
    private _actRoute : ActivatedRoute
  ) {

    this.id = this._actRoute.snapshot.paramMap.get("id");

    

    this.stuForm = this._fb.group({
      id : null,
      name : ["",Validators.required],
      age : [null, Validators.required],
      city : ["", Validators.required]
    })


    if(this.id){
      this._stu.getStudentById(this.id).subscribe(result=>{
        this.stuForm.setValue(result);
      })
    }
   }

  ngOnInit(): void {
  }
  submit(){
    if(this.stuForm.invalid){
      this.checkForm = true;
      return;
    }
    if(this.id){
      this._stu.updateStudent(this.id, this.stuForm.value).subscribe(result=>{
        this._router.navigate(["/student/list"])
      })
    }else{

      this._stu.addStudent(this.stuForm.value).subscribe(result=>{
        // console.log(result);
        this._router.navigate(["/student/list"])
      })
    }


  }

}

<div class="container">
    <form [formGroup]="stuForm">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="form-group">
                <label for="">Full Name</label>
                <input type="text" class="form-control" formControlName="name" [ngClass]="{'is-invalid' : checkForm && stuForm.controls['name'].errors }" />
            </div>
            <div class="form-group">
                <label for="">Age</label>
                <input type="text" class="form-control" formControlName="age" [ngClass]="{'is-invalid' : checkForm && stuForm.controls['age'].errors }" />
            </div>
            <div class="form-group">
                <label for="">City</label>
                <select formControlName="city" class="form-control" [ngClass]="{'is-invalid' : checkForm && stuForm.controls['city'].errors }" >
                    <option value="">Select</option>
                    <option value="indore">Indore</option>
                    <option value="mumbai">Mumbai</option>
                    <option value="pune">Pune</option>
                    <option value="bhopal">Bhopal</option>
                </select>
            </div>
            <br />
            <Br />
            <input type="submit" value="{{ id ? 'Update' : 'Add' }}" class="btn btn-primary" (click)="submit()" />
        </div>
    </div>
    </form>
</div>

// react/pro4/src/root/components/pages/Student/Student.js
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { saveData, getDataById, updateData } from '../../../../services/StudentService';
let Student = ()=>{
    // let [fullName, setFullName] = useState("");
    // let [age, setAge] = useState("");
    // let [city, setCity] = useState("");

    let navigate = useNavigate();
    let params = useParams();
    // console.log(params);
    let [user, setUser] = useState({})
        useEffect(()=>{
            
                if(params.id){
                    
                    getDataById(params.id).then(result=>{
                            setUser(result.data);
                        })
                    }else{
                    
                        setUser({
                            name : "",
                            age : "",
                            city : ""
                        })
                    }
                
            
        }, [params.id])
    


    let setData = (e, attr)=>{
        setUser((prevData)=>({...prevData,  [attr] : e.target.value}));
        // setUser((prevData)=> {...prevData, [attr] : e.target.value} )
    }


    let save = ()=>{
        // axios.post("http://localhost:4200/student", user).then(result=>{
        //     console.log(result.data);
        // })]
        if(params.id){
            updateData(params.id, user).then(result=>{
                navigate("/student/list");
            })
        }else{

            saveData(user).then(result=>{
                navigate("/student/list");
            })
        }
    }
    

    return(
        <>
            <div className="container my-5">
                <div className="row">
                    <div className="col-md-6 offset-md-3">
                        
                        <div className="form-group">
                            <label htmlFor="">Full Name</label>
                            <input type="text" value={user.name} onChange={(e)=>setData(e, "name")} className="form-control" />
                    
                        </div>
                        <div className="form-group">
                            <label htmlFor="">Age</label>
                            <input type="text" value={user.age} onChange={(e)=>setData(e, "age")} className="form-control" />
                    
                        </div>
                        <div className="form-group">
                            <label htmlFor="">City</label>
                            <select value={user.city} onChange={(e)=>setData(e, "city")} className="form-control" >
                                <option>Select</option>
                                <option>Indore</option>
                                <option>Mumbai</option>
                                <option>Pune</option>
                                <option>Delhi</option>
                            </select>
                    
                        </div>

                        <br />
                        <br />
                        <input type="button" onClick={save} className="btn btn-success"  value={params.id ? 'Update' : 'Add' } />
                    </div>
                </div>
            </div>
    
        </>
    )
}

export default Student;
